# Site settings
title: Clojurescript Made Easy
email: boston@clojurescriptmadeeasy.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing the good news of Clojurescript.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clojurescriptmadeeasy.com" # the base hostname & protocol for your site
twitter_username: bostonou
github_username: bostonou 

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /blog/:title.html
